//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapAccounts.Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abort.
        /// </summary>
        public static string ABORT_CALL {
            get {
                return ResourceManager.GetString("ABORT_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Search this address:.
        /// </summary>
        public static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bus stops.
        /// </summary>
        public static string BUS_STOPS {
            get {
                return ResourceManager.GetString("BUS_STOPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do you want to change the selected address?.
        /// </summary>
        public static string CHANGE_ADDRESS_WARN {
            get {
                return ResourceManager.GetString("CHANGE_ADDRESS_WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contact.
        /// </summary>
        public static string CONTACT {
            get {
                return ResourceManager.GetString("CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contact page.
        /// </summary>
        public static string CONTACT_PAGE {
            get {
                return ResourceManager.GetString("CONTACT_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Details and reports.
        /// </summary>
        public static string DETAILS_REPORTS {
            get {
                return ResourceManager.GetString("DETAILS_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Download images.
        /// </summary>
        public static string DOWNLOAD_IMAGES {
            get {
                return ResourceManager.GetString("DOWNLOAD_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set the upper left and bottom right corners of a region:.
        /// </summary>
        public static string GD_STEP1 {
            get {
                return ResourceManager.GetString("GD_STEP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Press collect streets if the selected region is correct..
        /// </summary>
        public static string GD_STEP2 {
            get {
                return ResourceManager.GetString("GD_STEP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Choose a street or visualize the region&apos;s images..
        /// </summary>
        public static string GD_STEP3 {
            get {
                return ResourceManager.GetString("GD_STEP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Get streets.
        /// </summary>
        public static string GET_STREETS {
            get {
                return ResourceManager.GetString("GET_STREETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Home.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Home page.
        /// </summary>
        public static string HOME_PAGE {
            get {
                return ResourceManager.GetString("HOME_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hospitals.
        /// </summary>
        public static string HOSPITALS {
            get {
                return ResourceManager.GetString("HOSPITALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filter street cracks.
        /// </summary>
        public static string IMG_CRACKS {
            get {
                return ResourceManager.GetString("IMG_CRACKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Custom filter.
        /// </summary>
        public static string IMG_CUSTOM {
            get {
                return ResourceManager.GetString("IMG_CUSTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a See images.
        /// </summary>
        public static string IMG_ORIG {
            get {
                return ResourceManager.GetString("IMG_ORIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filter trees.
        /// </summary>
        public static string IMG_TREES {
            get {
                return ResourceManager.GetString("IMG_TREES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Use this control to navigate among the points retrieved:.
        /// </summary>
        public static string LOCATION_SLIDER_HELP {
            get {
                return ResourceManager.GetString("LOCATION_SLIDER_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Find more points.
        /// </summary>
        public static string MORE_POINTS {
            get {
                return ResourceManager.GetString("MORE_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a With this option all the points belonging to the selected street will be interpolated in order to find more images of the street. The waiting time may increase..
        /// </summary>
        public static string MORE_POINTS_HELP {
            get {
                return ResourceManager.GetString("MORE_POINTS_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Next image.
        /// </summary>
        public static string NEXT_IMAGE {
            get {
                return ResourceManager.GetString("NEXT_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It wasn&apos;t possible to get any picture for this street. \n.
        /// </summary>
        public static string NO_IMAGES_1 {
            get {
                return ResourceManager.GetString("NO_IMAGES_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  pictures in wrong addresses\n.
        /// </summary>
        public static string NO_IMAGES_2 {
            get {
                return ResourceManager.GetString("NO_IMAGES_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  locations without pictures..
        /// </summary>
        public static string NO_IMAGES_3 {
            get {
                return ResourceManager.GetString("NO_IMAGES_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a There&apos;s.
        /// </summary>
        public static string OK_IMAGES_1 {
            get {
                return ResourceManager.GetString("OK_IMAGES_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  picture(s) available for this address. \n.
        /// </summary>
        public static string OK_IMAGES_2 {
            get {
                return ResourceManager.GetString("OK_IMAGES_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  picture(s) in wrong address(es). \n.
        /// </summary>
        public static string OK_IMAGES_3 {
            get {
                return ResourceManager.GetString("OK_IMAGES_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  position(s) without picture(s)..
        /// </summary>
        public static string OK_IMAGES_4 {
            get {
                return ResourceManager.GetString("OK_IMAGES_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pause.
        /// </summary>
        public static string PAUSE {
            get {
                return ResourceManager.GetString("PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pharmacies.
        /// </summary>
        public static string PHARMACIES {
            get {
                return ResourceManager.GetString("PHARMACIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Play.
        /// </summary>
        public static string PLAY {
            get {
                return ResourceManager.GetString("PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Previous image.
        /// </summary>
        public static string PREV_IMAGE {
            get {
                return ResourceManager.GetString("PREV_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Region of Interest.
        /// </summary>
        public static string ROI {
            get {
                return ResourceManager.GetString("ROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save sessions.
        /// </summary>
        public static string SAVE_SESSION {
            get {
                return ResourceManager.GetString("SAVE_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Schools.
        /// </summary>
        public static string SCHOOLS {
            get {
                return ResourceManager.GetString("SCHOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Search.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a See heatmap.
        /// </summary>
        public static string SEE_HEATMAP {
            get {
                return ResourceManager.GetString("SEE_HEATMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a See streets.
        /// </summary>
        public static string SEE_STREETS {
            get {
                return ResourceManager.GetString("SEE_STREETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Choose an operation:.
        /// </summary>
        public static string SELECT_OPERATION {
            get {
                return ResourceManager.GetString("SELECT_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Insert the address of the endpoint that will process the images:.
        /// </summary>
        public static string SET_FILTER_ENDPOINT {
            get {
                return ResourceManager.GetString("SET_FILTER_ENDPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a See heatmap.
        /// </summary>
        public static string TG_HEATMAP {
            get {
                return ResourceManager.GetString("TG_HEATMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Trees.
        /// </summary>
        public static string TREES {
            get {
                return ResourceManager.GetString("TREES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unset street.
        /// </summary>
        public static string UNSET_STREET {
            get {
                return ResourceManager.GetString("UNSET_STREET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Visualize.
        /// </summary>
        public static string VISUALIZE {
            get {
                return ResourceManager.GetString("VISUALIZE", resourceCulture);
            }
        }
    }
}
